### PR TITLE
fix: Change "created_by" value type in system clients table to be UUID

### LINKED ISSUE #11971: Change "created_by" value type in system clients table to be UUID

### PR DESCRIPTION
**Pull request by jamil314**
## Description

Clearly describe what has been changed. Include relevant context or background.
Explain how the issue was fixed (if applicable) and the root cause.

Link this pull request to the GitHub issue (and optionally name the branch `ocrvs-<issue #>`)

## Checklist

- [ ] I have linked the correct Github issue under "Development"
- [ ] I have tested the changes locally, and written appropriate tests
- [ ] I have tested beyond the happy path (e.g. edge cases, failure paths)
- [ ] I have updated the changelog with this change (if applicable)
- [ ] I have updated the GitHub issue status accordingly

### CODE REVIEW

File: packages/migration/src/migrations/events/1777359097847_alter-system-clients-created-by-to-uuid.sql [hunk 1]
```diff
@@ -0,0 +1,5 @@
+-- Up Migration
+ALTER TABLE system_clients ALTER COLUMN created_by TYPE UUID USING created_by::UUID;
```
Comment (naftis) [inline packages/migration/src/migrations/events/1777359097847_alter-system-clients-created-by-to-uuid.sql:2]: Should the `created_by` be a foreign key reference to `users.id`?

Comment (jamil314) [reply packages/migration/src/migrations/events/1777359097847_alter-system-clients-created-by-to-uuid.sql:2]: Yeah, makes sense. :+1:

**Comment by jamil314** [comment]
Will continue after [this](https://github.com/opencrvs/opencrvs-core/pull/12213) is merged.

File: packages/events/src/service/reindex/reindex.test.ts [hunk 2]
```diff
@@ -223,15 +225,15 @@ beforeEach(async () => {
 })
 
 test(`prevents forbidden access if missing required scope`, async () => {
-  const client = createSystemTestClient('test-system', [])
+  const client = createSystemTestClient(TEST_SYSTEM_ID, [])
```
Comment (Nil20) [inline packages/events/src/service/reindex/reindex.test.ts:228]: parameter of the func `createSystemTestClient` can be now converted to UUID

File: packages/events/src/service/reindex/reindex.test.ts [hunk 3]
```diff
@@ -79,7 +81,7 @@ const singleEventConfigHandler = http.get(
 )
 
 const reindexToken = createTestToken({
```
Comment (Nil20) [inline packages/events/src/service/reindex/reindex.test.ts:83]: parameter of the func `createTestToken` can be  converted to UUID

File: packages/events/src/tests/utils.ts [hunk 4]
```diff
@@ -57,6 +57,10 @@ import {
   setupHierarchyWithUsers
 } from './generators'
 
+export const TEST_SYSTEM_ID = '00000000-0000-1000-8000-000000000001' as UUID
+export const TEST_SYSTEM_ID_2 = '00000000-0000-1000-8000-000000000002' as UUID
+export const REINDEX_SYSTEM_ID = '00000000-0000-1000-8000-000000000003' as UUID
```
Comment (Nil20) [inline packages/events/src/tests/utils.ts]: The nil UUID has defined meaning in the UUID spec (it's the "absence of a UUID"). Using it as a real system identity in tokens could be fragile — any future validation that rejects the nil UUID (e.g. a stricter Zod schema or a middleware check for non-zero IDs) would silently break reindex. A fixed deterministic UUID (e.g. v5 from a namespace) or just getUUID() once and hardcode it would be cleaner, unambiguous and safer.

**Review by Nil20 — APPROVED** [review]
LGTM! 👍 Make sure to run `yarn generate-db-types` and `yarn generate-db-schema` in `packages/events` after running the up migration. Should help out if any remaining tests/types needs to be updated.
