### PR TITLE
fix(qr-code): page crash on verify certificate and add missing registrar information

### LINKED ISSUE #6230: QR code is currently not working- getting invalid QR for all certificates
**Bug description:**
QR code is currently not working- getting invalid QR for all certificates

**Steps to reproduce:**
1. Login to Registrar
2. Print any certificate
3. Scan the QR code

**Actual result:**
QR code is currently not working- getting invalid QR for all certificates

**Expected result:**
QR code should be working
 
**Screen record:**
invalid qr

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

### LINKED ISSUE #6422: System crash occurs when try to open QR given that Gender of child or deceased is "unknown"
**Bug description:**
System crash occurs when try to open QR given that Gender of child or deceased is "unknown"

**Steps to reproduce:**
1. Login to RA/ registrar
2. Go to Ready to print
3. Download any birth/death certificate where Gender of child or deceased is "unknown"
4. Go to certificate preview page
5. Scan QR code

**Actual result:**
System crash occurs when try to open QR given that Gender of child or deceased is "unknown"

**Expected result:**
Should be able to verify through QR code  given that Gender of child or deceased is "unknown"

**Screenshot:**
qr code bug

**Tested on:**
https://login.farajaland-qa.opencrvs.org/?lang=en

### LINKED ISSUE #6614: Registration center and name of registrar is missing when Scan a birth QR code
**Bug description:**
Registration center and name of registrar is missing when Scan a birth QR code

**Steps to reproduce:**
1. Scan a birth qr code
2.  Observe

**Actual result:**
Registration center and name of registrar is missing when Scan a birth QR code
**Expected result:**
Should show registration place and registrar's name

**Screen recording:**

brth

**Environment:**
https://login.farajaland-qa.opencrvs.org/?lang=en

**Version:**
V1.5.0

### PR DESCRIPTION
**Pull request by naftis**
fixes #6422 where the verify certificate page crashes when gender is unknown
fixes #6614 where the verify certificate page is missing registrar information
fixes #6230 where the verify certificate page crashes on death certificate

### CODE REVIEW

File: packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx [hunk 1]
```diff
@@ -317,38 +325,40 @@ export function VerifyCertificatePage() {
...
       )
     }
+
     if (data.registration?.type === RegistrationType.Death) {
       return (
-        data?.deceased?.name[0]?.firstNames +
+        data.deceased?.name?.[0]?.firstNames +
         ' ' +
-        data?.deceased?.name[0]?.familyName
+        data.deceased?.name?.[0]?.familyName
```
Comment (naftis) [inline packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx:341]: @Zangetsu101 hardcoded name generation... would probably be smart to refactor at the same time

File: packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx [hunk 2]
```diff
@@ -508,24 +507,24 @@ export function VerifyCertificatePage() {
                       }
                       value={
                         <Text variant={'reg16'} element={'span'}>
-                          {getChildOrDeceasedData(currentData).fullName}
+                          {getFullName(data)}
```
Comment (naftis) [inline packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx:510]: this "getXyz" paradigm isn't necessary We should rather early-return the loading state if data is not loaded, and then directly render the stuff we want without single-use helper functions. This component would be simpler that way. I can look into refactoring this.

File: packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx [hunk 3]
```diff
@@ -389,8 +399,8 @@ export function VerifyCertificatePage() {
       .join(', ')
   }
 
-  const getRegistarData = (data: any) => {
-    const history = data.history.find(
```
Comment (naftis) [inline packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx:393]: Wonder why no errors appear when using "any" here, we should look into enabling that. We have gateway types so there is no reason to do this.

File: packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx (hunk 1 above)
Comment (Zangetsu101) [reply packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx]: We should be able to use this: https://github.com/opencrvs/opencrvs-core/blob/624f6b8ac310472d3966ade57bb9131b4632d6ef/packages/client/src/utils/data-formatting.ts#L26

File: packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx (hunk 2 above)
Comment (Zangetsu101) [reply packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx:393]: yeah we could even use `isBirthRegistration` early on recordDetails to render entirely different component like `<BirthVerifyDetails>` & `<DeathVerifyDetails>`

File: packages/client/src/views/VerifyCertificate/useVerificationRecordDetails.ts [hunk 4]
```diff
@@ -0,0 +1,126 @@
...
+
+const FETCH_RECORD_DETAILS_FOR_VERIFICATION = gql`
+  query fetchRecordDetailsForVerification($id: String!) {
+    fetchRecordDetailsForVerification(id: $id) {
+      ... on BirthRegistration {
+        id
+        child {
+          name {
+            firstNames
+            familyName
```
Comment (Zangetsu101) [inline packages/client/src/views/VerifyCertificate/useVerificationRecordDetails.ts:24]: Hm I must have missed adding middle name field here. Will need to open a PR on the release branch. We really need to refactor the queries to use fragments otherwise these types of bugs will keep coming

File: packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx (hunk 2 above)
Comment (naftis) [reply packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx:393]: Let's leave the refactoring for another PR if we wanna do it. Let's fix the bug here

**Comment by naftis** [comment]
- [ ] CHANGELOG
- [ ] test that the verify page works as expected

**Review by Zangetsu101 — APPROVED** [review]

File: packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx (hunk 1 above)
Comment (Zangetsu101) [reply packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx]: okay sounds good
