### PR TITLE
fix: show username label in user create/edit review

### LINKED ISSUE #12344: 'User name' fieldname not appearing on confirm details page in the user creation/ edit flow.
**Bug description:**
'User name' fieldname not appearing on confirm details page in the user creation/ edit flow.

**Steps to reproduce:**
1. Login as j.campbell.
2. Navigate to Confirm details page in the user creation/ edit flow.
3. Observe user details section.

**Actual result:**
'User name' fieldname not appearing on confirm details page in the user creation/ edit flow.

**Expected result:**
Fieldname should appear correctly.

**Screenshot:**
Image

**Tested on:**
https://register.v20-test.e2e-k8s.opencrvs.dev/

**Version:**
v2.0

### PR DESCRIPTION
**Pull request by jamil314**
## Description
image

[Countryconfig PR](https://github.com/opencrvs/opencrvs-countryconfig/pull/1392)

## Checklist

- [ ] I have linked the correct Github issue under "Development"
- [ ] I have tested the changes locally, and written appropriate tests
- [ ] I have tested beyond the happy path (e.g. edge cases, failure paths)
- [ ] I have updated the changelog with this change (if applicable)
- [ ] I have updated the GitHub issue status accordingly

### CODE REVIEW

File: packages/client/src/views/SysAdmin/Team/user/userEditor/UserEditor.tsx [hunk 1]
```diff
@@ -120,7 +120,7 @@ function getUserEditConfig(
               type: FieldType.NAME,
               required: true,
               hideLabel: true,
-              label: emptyMessage
+              label: messages.username
```
Comment (makelicious) [inline packages/client/src/views/SysAdmin/Team/user/userEditor/UserEditor.tsx]: `user name != username` I got bit confused since label does not match the value

for username, I would expect `k.mweene` or similar

Comment (jamil314) [reply packages/client/src/views/SysAdmin/Team/user/userEditor/UserEditor.tsx]: @tiri39 `Username` or `User name` ?

Comment (jamil314) [reply packages/client/src/views/SysAdmin/Team/user/userEditor/UserEditor.tsx]: or `Full name`?

Comment (tiri39) [reply packages/client/src/views/SysAdmin/Team/user/userEditor/UserEditor.tsx]: We used to have separate fields for first name and surname, but now that it’s a single field, “User’s full name” sounds better.
Screenshot 2026-04-22 134609

**Review by makelicious — APPROVED** [review]
