### PR TITLE
OCRVS 3800 / Fix `<PageHeader>` being 1px too tall

### LINKED ISSUE #3800: Fix `<PageHeader>` being 1px too tall
`EventTopBar` is 56px (correct). `PageHeader` is 57px

### PR DESCRIPTION
**Pull request by naftis**
Fixes #3800

### CODE REVIEW

File: packages/components/src/components/interface/Header/PageHeader.tsx [hunk 1]
```diff
@@ -15,7 +15,8 @@ import styled from 'styled-components'
 import { IDomProps } from './AppHeader'
 
 const PageHeaderWrapper = styled.div`
-  padding: 8px 16px;
+  padding: 0 ${({ theme }) => theme.grid.margin}px;
```
Comment (naftis) [inline packages/components/src/components/interface/Header/PageHeader.tsx:18]: Use 16px

**Review by jpye-finch — APPROVED** [review]
